name: Deploy Frontend to Test

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TEST_SSH_KEY }}

      - name: Add server to known hosts
        run: ssh-keyscan -H ${{ secrets.TEST_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy dist to server
        run: |
          rsync -avz --delete \
          dist/ \
          ${{ secrets.TEST_USER }}@${{ secrets.TEST_HOST }}:${{ secrets.TEST_PATH }}/